### ISSUE TITLE
On search show drop down with results of  user

### ISSUE THREAD

**Issue by rawasaditya** [rawasaditya/SocioPedia#23]
When one search in searchbox show dropdown with list of matching users showing first and last name along with profile picture
Example component is [here](https://mui.com/material-ui/react-autocomplete/#google-maps-place)
In order to achieve this following has to be done.

- [x] Create router for search in server\routes\users.js
- [x] Create controller for search in server\controller\users.js
- [x] Search query should include first and last name, that means user can search by first name and last name
- [ ] Component has to be material UI example mentioned above
- [ ] After clicking on the result one should be redirected to profile page 

![image](https://github.com/rawasaditya/SocioPedia/assets/114228121/6276d2fa-ac78-43af-b76c-4dbcdf210078)

**Comment by elidakirigo** [comment]
hello, I'd love to assist in creating the dropdowns on this issue, thanks

**Comment by rawasaditya** [comment]
@elidakirigo do contribute and provide screenshot along with PR

**Comment by elidakirigo** [comment]
@rawasaditya okay.

**Comment by rawasaditya** [comment]
Anyupdate @elidakirigo  ?

**Comment by elidakirigo** [comment]
almost @rawasaditya

**Comment by rawasaditya** [comment]
End point created  ``/api/v1/user/search``
with following response
`[
  {
    "_id": "6490fce742170c0d593144c6",
    "firstName": "Aditya",
    "lastName": "Rawas",
    "email": "rawasaditya@gmail.com",
    "picturePath": "profile pic.jpg",
    "friends": [
      "648e6c6a69b41bca4c48555c"
    ],
    "location": "India",
    "occupation": "Software Developer",
    "createdAt": "2023-06-20T01:12:07.133Z",
    "updatedAt": "2023-06-24T07:18:26.077Z",
    "__v": 40,
    "twitter": "https://twitter.com/rawas_aditya",
    "linkedIn": "https://www.linkedin.com/in/aditya-rawas-626578149/"
  }
]`

**Comment by elidakirigo** [comment]
> End point created `/api/v1/user/search` with following response `[ { "_id": "6490fce742170c0d593144c6", "firstName": "Aditya", "lastName": "Rawas", "email": "rawasaditya@gmail.com", "picturePath": "profile pic.jpg", "friends": [ "648e6c6a69b41bca4c48555c" ], "location": "India", "occupation": "Software Developer", "createdAt": "2023-06-20T01:12:07.133Z", "updatedAt": "2023-06-24T07:18:26.077Z", "__v": 40, "twitter": "https://twitter.com/rawas_aditya", "linkedIn": "https://www.linkedin.com/in/aditya-rawas-626578149/" } ]`

noted @rawasaditya

**Comment by elidakirigo** [comment]
@rawasaditya update, i have added mui to the dropdown, whats left is adding the api data

**Comment by rawasaditya** [comment]
This looks great create PR will populate rest and update again, create PR
