### ISSUE TITLE
Generate notification, create endpoint 

### ISSUE THREAD

**Issue by rawasaditya** [rawasaditya/SocioPedia#24]
Create endpoint to generate notifications, notification has to be generated when 
- User add friends, notification should go to friends that **someone has added them as friend** notification message should be "XYZ added you as friend"
- Friends create new posts

- [x] Create router at  server\routes\users.js
- [x] Create controller at server\routes\users.js

**Comment by rawasaditya** [comment]
Frontend implementation is like this
![image](https://github.com/rawasaditya/SocioPedia/assets/114228121/7473d465-0f37-4e3b-99dd-e88916e2ab38)

**Comment by sigmacoder25** [comment]
Assign me.

**Comment by rawasaditya** [comment]
@sigmacoder25  Thank you so much for your contribution! Your efforts are greatly appreciated and will go a long way in improving our project. Please feel free to share it with others and Star the repo to help us grow even further!
