### ISSUE TITLE
Change workflow name "Hello World workflow" to "Project setup workflow"

### ISSUE THREAD

**Issue by rawasaditya** [rawasaditya/SocioPedia#32]
Only effort is to change _name:Hello World workflow_ to _name:Project setup workflow_ in main.yml file

**Comment by neeravbhaskarla** [comment]
hi can I get it assigned

**Comment by rawasaditya** [comment]
@neeravbhaskarla assigned

**Comment by neeravbhaskarla** [comment]
Hi @rawasaditya made a PR, with the required changes. Please check
