### ISSUE TITLE
When toggled to dark mode and refreshed application will switches back to light mode

### ISSUE THREAD

**Issue by rawasaditya** [rawasaditya/SocioPedia#36]
Refer video for bug

https://github.com/rawasaditya/SocioPedia/assets/114228121/9ec0bb36-41db-431a-8040-ecdb74291cda

Approach to fix
- Save toggle state in browsers storage and on mount change components state based on browser stored state

**Comment by neeravbhaskarla** [comment]
Hi, Can I get it assigned?

**Comment by neeravbhaskarla** [comment]
Hi @rawasaditya, made required change and made a PR. Please check

**Comment by rawasaditya** [comment]
Thanks for your contribution @neeravbhaskarla
