### ISSUE TITLE
When visited to other user profile show add/remove user icons

### ISSUE THREAD

**Issue by rawasaditya** [rawasaditya/SocioPedia#39]
Show icons here
import icons from here
``import { PersonAddOutlined, PersonRemoveOutlined } from "@mui/icons-material";``
![image](https://github.com/rawasaditya/SocioPedia/assets/114228121/82bdc303-f28b-45e3-8a62-993b3548388b)

**Comment by ParthBoghani46** [comment]
hey , i am beginner in open source contribution . and i am egar to solve this issue can you guide and assign to me

**Comment by github2python** [comment]
@rawasaditya , I wanted to work on this ,please can you assign this to me

**Comment by theQuery** [comment]
I'd like to be assigned to this if it's possible

**Comment by rawasaditya** [comment]
Fixed
