### ISSUE TITLE
[ UI ] On clicking gear icon in profile page open form to update details

### ISSUE THREAD

**Issue by rawasaditya** [rawasaditya/SocioPedia#40]
When in **Profile** page onclicking form should open up to update following details

- picture
- location
- occupation
- linkedIn
- twitter
- instagram

**Comment by jgyfutub** [comment]
I am interested to work upon this issue but after running the frontend folder with command npm run dev, an error was surfacing that autoprefixer is not installed (postcss.config.js file is not there).Even after installing autoprefixer by npm and putting postcss.config.js file the same error was resurfacing again,plz tell me a solution for it.

**Comment by rawasaditya** [comment]
run npm ci in frontend folder first then hit npm run dev

**Comment by jgyfutub** [comment]
i did this but same error is coming
`Error: Loading PostCSS Plugin failed: Cannot find module 'autoprefixer'
Require stack:
- C:\Users\Acer\postcss.config.js`
