### ISSUE TITLE
Remove gear icon from home page

### ISSUE THREAD

**Issue by rawasaditya** [rawasaditya/SocioPedia#41]
Remove **gear** icon from **home** page and make sure when, you click on name of user you should be redirected to profile page of user

- [ ] Remove gear icon
- [ ] On clicking user's name one should go to its profile page 

![image](https://github.com/rawasaditya/SocioPedia/assets/114228121/b9897515-80c6-45e2-8666-97355a6fb017)

**Comment by ParthBoghani46** [comment]
hi, i am new to open source ,can you guide and assign this issue to me

**Comment by rawasaditya** [comment]
@ParthBoghani46 
For first task in UserWidger/index.js remove following code
![SmartSelect_20230630_091226_Chrome](https://github.com/rawasaditya/SocioPedia/assets/114228121/08dda0f0-a42f-4c40-bbb7-5b3322a2dacd)

for second task add
`onClick={() => navigate(`/profile/${_id}`)}`

here in Typography
![SmartSelect_20230630_091312_Chrome](https://github.com/rawasaditya/SocioPedia/assets/114228121/ec99a22f-f7b8-46df-afc1-56131bf8c91f)

**Comment by ParthBoghani46** [comment]
Thanks for your guidance
