### ISSUE TITLE
Remove Attachment button and Icon

### ISSUE THREAD

**Issue by rawasaditya** [rawasaditya/SocioPedia#42]
from MyPostWidget/index.jsx remove following Attachment button completely
![image](https://github.com/rawasaditya/SocioPedia/assets/114228121/3190ab71-8804-489e-b6f5-3f95d5239afe)

**Comment by ParthBoghani46** [comment]
hi , i am new to open source ,i am eager to do this issue.can you assign to me

**Comment by rawasaditya** [comment]
assigned, please provide Screenshot along with your PR, thanks

**Comment by ParthBoghani46** [comment]
hey i get some problem when i run a server 
![Screenshot from 2023-06-30 10-02-25](https://github.com/rawasaditya/SocioPedia/assets/135826677/6b5e6ca1-c4a7-409f-9acc-5f59934d6eae)

**Comment by ParthBoghani46** [comment]
hey i got issue when i run backend
![Screenshot from 2023-06-30 15-17-31](https://github.com/rawasaditya/SocioPedia/assets/135826677/d9c1ae8e-8a13-4e20-99e4-2808882a7615)

**Comment by fiskryeziu** [comment]
run the command 
```shell
mongod
```
to start the server locally.I'm assuming you have installed the mongodb.

**Comment by rawasaditya** [comment]
Yeah, Looks like your mongodb is not running

**Comment by ParthBoghani46** [comment]
i got some when i  run app.app is not running
![Screenshot from 2023-06-30 22-08-48](https://github.com/rawasaditya/SocioPedia/assets/135826677/297c59b7-f66e-4cab-b751-89a2dd78aee1)

**Comment by rawasaditya** [comment]
Sync with main branch, this issue is fixed

**Comment by rawasaditya** [comment]
ia this issue gone ? @ParthBoghani46

**Comment by rawasaditya** [comment]
I have merged new [PR](https://github.com/rawasaditya/SocioPedia/pull/47) this should fix it, thanks

**Comment by theQuery** [comment]
This issue should probably be closed, right?
