### ISSUE TITLE
[BACKEND] Creating endponit to send patch request to update following

### ISSUE THREAD

**Issue by rawasaditya** [rawasaditya/SocioPedia#44]
1. picture
2. location
3. occupation
4. linkedIn
5. twitter
6. instagram

**Comment by jgyfutub** [comment]
can I work on this issue?,I am new to open source and interested to collaborate in the issue

**Comment by rawasaditya** [comment]
@jgyfutub Welcome to the journey, I am assigning this issue

**Comment by jgyfutub** [comment]
@rawasaditya do I also I have to make changes in frontend so that server can accept the linkedin twitter instagram links from client?

**Comment by rawasaditya** [comment]
@jgyfutub  your PR is merged, if you wish to work on frontend #40  is the way to do it, thanks for your contribution look forward for more contribution, please share repo to more contributors and leave start  😊
