### ISSUE TITLE
Issue: Frontend Not Rendering due to "Uncaught TypeError: createTheme_default is not a function"

### ISSUE THREAD

**Issue by fiskryeziu** [rawasaditya/SocioPedia#45]
## Description
An error is encountered in the frontend. The error message states: "Box.js:6 Uncaught TypeError: createTheme_default is not a function." This issue prevents the application from functioning as expected.

## Expected Behavior
The application should load without any errors and function as intended.

## Actual Behavior
Upon accessing the frontend, the browser console displays the following error message:

``
Box.js:6 Uncaught TypeError: createTheme_default is not a function
    at Box.js:6:22
``

**Comment by rawasaditya** [comment]
Have you tried updating your main branch to latest ?
I think this is fixed already can you confirm this again

**Comment by rawasaditya** [comment]
Thanks for reporting this issue will submit PR soon
