### ISSUE TITLE
Remove favicon and change title

### ISSUE THREAD

**Issue by rawasaditya** [rawasaditya/SocioPedia#59]
from frontend/index.html
Remove ` <link rel="icon" type="image/svg+xml" href="/vite.svg" />`
and change title from Vite + React to "SocioPedia | Growing together"

**Comment by Pulkitxm** [comment]
Can I get assigned? let me know how to start

**Comment by rawasaditya** [comment]
@Pulkitxm its simple task goto index.html file and remove and update above mentioned changes

**Comment by snehalchaudhari98** [comment]
Hey @rawasaditya , I'm new to the community, and I'm interested in working on this issue. If this issue isn't assigned to a contributor, I'd like to work on it.

**Comment by rawasaditya** [comment]
@randomcoder5 Thank you for your invaluable contributions to our open-source project. We appreciate your dedication and encourage you to continue sharing your expertise. Your involvement is crucial for the project's growth and success.
