### ISSUE TITLE
Create Profile Page

### ISSUE THREAD

**Issue by rawasaditya** [rawasaditya/SocioPedia#6]

**Comment by KarthikShetty5** [comment]
I can do this, assign it

**Comment by Pulkitxm** [comment]
Can I get assigned ?

**Comment by rawasaditya** [comment]
@Pulkitxm Once developed do provide Screenshot

**Comment by Pulkitxm** [comment]
Hey how to set-uo the local env. ? and the dependencies ??

**Comment by rawasaditya** [comment]
Profile page added with [PR](https://github.com/rawasaditya/SocioPedia/pull/13)
