### ISSUE TITLE
Making change to UI for comment box

### ISSUE THREAD

**Issue by rawasaditya** [rawasaditya/SocioPedia#62]
1. Show hide input box of comment section on button click
2. flex inputbase and button
3. remove padding and make input box small

![image](https://github.com/rawasaditya/SocioPedia/assets/114228121/338c5467-3964-43c5-b9bc-78393731daca)

**Comment by theQuery** [comment]
I'd love to work on fixing this. Assign me, please

**Comment by theQuery** [comment]
Shouldn't this be closed?

**Comment by rawasaditya** [comment]
closing
