### ISSUE TITLE
Comment on post and display all comments 

### ISSUE THREAD

**Issue by rawasaditya** [rawasaditya/SocioPedia#7]
Currently we are not showing comment counts and comments nor we are able to comment at all.

**Comment by iamworrell** [comment]
can you assign this issue to me?

**Comment by rawasaditya** [comment]
@iamworrell You will have to create endpoints as well

**Comment by iamworrell** [comment]
ok no problem, is there a deadline to complete this issue?

**Comment by rawasaditya** [comment]
@iamworrell (Read Rules here)[https://github.com/rawasaditya/SocioPedia#how-to-contribute]
There is no dead line but there is 3 days of limited time within which you will have to provide some update, thanks

**Comment by iamworrell** [comment]
@rawasaditya I managed to send comments to the database by postman, now i will work on doing it in the actual front-end

**Comment by rawasaditya** [comment]
Great! thanks for update @iamworrell

**Comment by iamworrell** [comment]
I added the functionality of posting comments to the database, now i will start working on getting comments and outputting them for their respective posts.

**Comment by iamworrell** [comment]
ok so I managed to send comments to the database and output them to the UI but im still working on the UI.

**Comment by rawasaditya** [comment]
can you share me branch where I can see these updates. Thanks

**Comment by iamworrell** [comment]
ok I will do it later today

**Comment by iamworrell** [comment]
I just made a pull request

**Comment by iamworrell** [comment]
@rawasaditya I just made a pull request

**Comment by rawasaditya** [comment]
Is, this [PR](https://github.com/rawasaditya/SocioPedia/pull/46) supposed be fix or is it just for reference as I asked for. Please sync with main branch since lot of issues are getting resolved your PR seems to be 2 commits behind already. 
Also it does not pass lint pipline

**Comment by iamworrell** [comment]
This is the first pull request I've done so I dont know what lint pipline means. The pull request is just for reference, also I didnt know that there was a commit criteria to be meant. I will merge with main and make two more commits.

**Comment by iamworrell** [comment]
I merged with main and pushed, still working on the lint pipline.

**Comment by rawasaditya** [comment]
No worries @iamworrell your PR shows 30 files changes, That is why I am concerned.
I see that you have made changes in controller and router, changes are great and looks good. Once you are done with you server side change do create a new PR with only those two files will merge your PR. In this way you will become contributor to the project and your name will reflect under contributors. Looking at efforts I will be really glad to make you one of the contributors

For frontend part will create another issue, which if you wish to contribute then will assign you

**Comment by iamworrell** [comment]
Still working on the server, I think I will be finished with the issue before the end of the week.

**Comment by iamworrell** [comment]
I will be finished with the issue by latest tomorrow.

**Comment by iamworrell** [comment]
I made a pull request

**Comment by iamworrell** [comment]
I made a new pull request, its able to merge and I only made changes in a few files.
