### ISSUE TITLE
Implement 404 page not found

### ISSUE THREAD

**Issue by rawasaditya** [rawasaditya/SocioPedia#9]
Currently when anyone visit link that does not exist will show bank page instead should show 404 page

**Comment by KarthikShetty5** [comment]
can u assign me this

**Comment by Pulkitxm** [comment]
Can I get assigned ?

**Comment by YashM** [comment]
Can I get assigned??

**Comment by rawasaditya** [comment]
Will merge first PR, I receive for this issue thanks

**Comment by rawasaditya** [comment]
Fixed
